export const investData = [
  {
    id: 1,
    type: "2 Bedroom",
    address: "4, Tonade, Ikeja, Lagos",
    fee: "800000",
    date: "18/10/2022",
    status: "Approved",
    amountPaid: "",
    withdraw: false,
  },
  {
    id: 2,
    type: "2 Bedroom",
    address: "11, Bode Thomas, Surulere, Lagos",
    fee: "700000",
    date: "17/10/2022",
    status: "Pending",
    amountPaid: "",
    withdraw: false,
  },
  {
    id: 3,
    type: "3 Bedroom",
    address: "256, LSPDC Estate, Meiran, Lagos",
    fee: "800000",
    date: "18/10/2022",
    status: "Closed",
    amountPaid: "10000",
    withdraw: false,
  },
  {
    id: 4,
    type: "2 Bedroom",
    address: "3, Arowolo, Yaba, Lagos",
    fee: "900000",
    date: "15/10/2022",
    status: "Approved",
    amountPaid: "",
    withdraw: false,
  },
  {
    id: 5,
    type: "2 Bedroom",
    address: "7, Jaiyeola, Ikeja, Lagos",
    fee: "800000",
    date: "18/10/2022",
    status: "Declined",
    amountPaid: "",
    withdraw: false,
  },
];
